"""Static list of RNLI lifeboat stations.

Generated from the RNLI open data station locations dataset (CSV export of
https://services1.arcgis.com/evM5NkxAYjTi6XPw/arcgis/rest/services/RNLI_Lifeboat_Station_locations/FeatureServer).

The launches API has no station-list endpoint and only exposes the 50 most
recent launches, so this list backfills the config-flow dropdown. Names can
differ slightly from the feed's shortName (e.g. "Bangor (Co Down)" vs
"Bangor"), which is why station matching is done on normalized base names.
"""
from typing import Any

STATIONS: dict[str, dict[str, Any]] = {
    "Aberdeen": {
        "label": "Aberdeen, City of Aberdeen",
        "latitude": 57.14405,
        "longitude": -2.08043,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/aberdeen-lifeboat-station",
        "what3words": "///vent.locked.chains",
        "station_type": "ALB",
    },
    "Aberdovey": {
        "label": "Aberdovey, Gwynedd",
        "latitude": 52.54316,
        "longitude": -4.04566,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/aberdovey-lifeboat-station",
        "what3words": "///fittingly.montage.rehearsal",
        "station_type": "ILB",
    },
    "Abersoch": {
        "label": "Abersoch, Gwynedd",
        "latitude": 52.82648,
        "longitude": -4.50444,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/abersoch-lifeboat-station",
        "what3words": "///tanks.chapters.parkland",
        "station_type": "ILB",
    },
    "Aberystwyth": {
        "label": "Aberystwyth, Dyfed",
        "latitude": 52.40875,
        "longitude": -4.08893,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/aberystwyth-lifeboat-station",
        "what3words": "///branch.grower.alerting",
        "station_type": "ILB",
    },
    "Achill Island": {
        "label": "Achill Island, Mayo",
        "latitude": 53.88277,
        "longitude": -9.94461,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/achill-island-lifeboat-station",
        "what3words": "///blackbirds.lessening.represent",
        "station_type": "ALB",
    },
    "Aith": {
        "label": "Aith, Shetland",
        "latitude": 60.28631,
        "longitude": -1.37521,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/aith-lifeboat-station",
        "what3words": "///revise.curiosity.clays",
        "station_type": "ALB",
    },
    "Aldeburgh": {
        "label": "Aldeburgh, Suffolk",
        "latitude": 52.15308,
        "longitude": 1.60276,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/aldeburgh-lifeboat-station",
        "what3words": "///pads.culminate.doubt",
        "station_type": "ALB",
    },
    "Alderney": {
        "label": "Alderney, Channel Isles",
        "latitude": 49.7241,
        "longitude": -2.20013,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/alderney-lifeboat-station",
        "what3words": "///hollies.predictable.souvenir",
        "station_type": "ALB",
    },
    "Amble": {
        "label": "Amble, Northumberland",
        "latitude": 55.33645,
        "longitude": -1.58168,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/amble-lifeboat-station",
        "what3words": "///sharpened.triangle.ambitions",
        "station_type": "ALB",
    },
    "Angle": {
        "label": "Angle, Dyfed",
        "latitude": 51.68939,
        "longitude": -5.07906,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/angle-lifeboat-station",
        "what3words": "///animate.emeralds.mirroring",
        "station_type": "ALB",
    },
    "Anstruther": {
        "label": "Anstruther, Fife",
        "latitude": 56.22144,
        "longitude": -2.69739,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/anstruther-lifeboat-station",
        "what3words": "///clotting.handbag.workbench",
        "station_type": "ALB",
    },
    "Appledore": {
        "label": "Appledore, Devon",
        "latitude": 51.05701,
        "longitude": -4.19978,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/appledore-lifeboat-station",
        "what3words": "///ants.wide.trending",
        "station_type": "ALB",
    },
    "Aran Islands": {
        "label": "Aran Islands, Galway",
        "latitude": 53.11983,
        "longitude": -9.66784,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/aran-islands-lifeboat-station",
        "what3words": "///follow.truces.envisage",
        "station_type": "ALB",
    },
    "Arbroath": {
        "label": "Arbroath, Angus",
        "latitude": 56.5553,
        "longitude": -2.58484,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/arbroath-lifeboat-station",
        "what3words": "///lands.appear.appeal",
        "station_type": "ALB",
    },
    "Arklow": {
        "label": "Arklow, Wicklow",
        "latitude": 52.79195,
        "longitude": -6.14506,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/arklow-lifeboat-station",
        "what3words": "///gifts.stud.sagged",
        "station_type": "ALB",
    },
    "Arran (Lamlash)": {
        "label": "Arran (Lamlash), Ayrshire and Arran",
        "latitude": 55.53526,
        "longitude": -5.12478,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/arran-lifeboat-station",
        "what3words": "///troll.dusted.patio",
        "station_type": "ILB",
    },
    "Arranmore": {
        "label": "Arranmore, Donegal",
        "latitude": 54.99697,
        "longitude": -8.49844,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/arranmore-lifeboat-station",
        "what3words": "///scrabbling.smooth.tone",
        "station_type": "ALB",
    },
    "Ballycotton": {
        "label": "Ballycotton, Cork",
        "latitude": 51.82696,
        "longitude": -8.00168,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/ballycotton-lifeboat-station",
        "what3words": "///broadening.subs.products",
        "station_type": "ALB",
    },
    "Ballyglass": {
        "label": "Ballyglass, Mayo",
        "latitude": 54.25379,
        "longitude": -9.89319,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/ballyglass-lifeboat-station",
        "what3words": "///battled.clad.compromises",
        "station_type": "ALB",
    },
    "Baltimore": {
        "label": "Baltimore, Cork",
        "latitude": 51.48772,
        "longitude": -9.37198,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/baltimore-lifeboat-station",
        "what3words": "///awakening.granules.imprecisely",
        "station_type": "ALB",
    },
    "Bangor (Co Down)": {
        "label": "Bangor (Co Down), Down",
        "latitude": 54.6657,
        "longitude": -5.66717,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/bangor-lifeboat-station",
        "what3words": "///slide.strict.admits",
        "station_type": "ILB",
    },
    "Barmouth": {
        "label": "Barmouth, Gwynedd",
        "latitude": 52.72095,
        "longitude": -4.05568,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/barmouth-lifeboat-station",
        "what3words": "///belief.both.mentions",
        "station_type": "ALB",
    },
    "Barra Island": {
        "label": "Barra Island, Western Isles",
        "latitude": 56.95412,
        "longitude": -7.48712,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/barra-island-lifeboat-station",
        "what3words": "///swordfish.trail.skews",
        "station_type": "ALB",
    },
    "Barrow": {
        "label": "Barrow, Cumbria",
        "latitude": 54.07251,
        "longitude": -3.17333,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/barrow-lifeboat-station",
        "what3words": "///acids.adapt.saving",
        "station_type": "ALB",
    },
    "Barry Dock": {
        "label": "Barry Dock, South Glamorgan",
        "latitude": 51.39315,
        "longitude": -3.2615,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/barry-dock-lifeboat-station",
        "what3words": "///paper.leap.king",
        "station_type": "ALB",
    },
    "Beaumaris": {
        "label": "Beaumaris, Gwynedd",
        "latitude": 53.26221,
        "longitude": -4.09085,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/beaumaris-lifeboat-station",
        "what3words": "///steaming.workloads.among",
        "station_type": "ILB",
    },
    "Bembridge": {
        "label": "Bembridge, Isle of Wight",
        "latitude": 50.68859,
        "longitude": -1.07244,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/bembridge-lifeboat-station",
        "what3words": "///saints.rentals.vessel",
        "station_type": "ALB",
    },
    "Berwick-Upon-Tweed": {
        "label": "Berwick-Upon-Tweed, Northumberland",
        "latitude": 55.76095,
        "longitude": -2.00027,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/berwick-upon-tweed-lifeboat-station",
        "what3words": "///shady.unable.ranks",
        "station_type": "ALB",
    },
    "Blackpool": {
        "label": "Blackpool, Lancashire",
        "latitude": 53.81344,
        "longitude": -3.0561,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/blackpool-lifeboat-station",
        "what3words": "///puff.exile.fires",
        "station_type": "ILB",
    },
    "Blyth": {
        "label": "Blyth, Northumberland",
        "latitude": 55.12559,
        "longitude": -1.49805,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/blyth-lifeboat-station",
        "what3words": "///kicks.invent.feeds",
        "station_type": "ILB",
    },
    "Borth": {
        "label": "Borth, Dyfed",
        "latitude": 52.4812,
        "longitude": -4.0514,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/borth-lifeboat-station",
        "what3words": "///gurgling.printing.paintings",
        "station_type": "ILB",
    },
    "Bridlington": {
        "label": "Bridlington, East Riding of Yorkshire",
        "latitude": 54.07849,
        "longitude": -0.19791,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/bridlington-lifeboat-station",
        "what3words": "///activity.warned.sprint",
        "station_type": "ALB",
    },
    "Brighton": {
        "label": "Brighton, East Sussex",
        "latitude": 50.81066,
        "longitude": -0.10384,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/brighton-lifeboat-station",
        "what3words": "///choice.regime.farm",
        "station_type": "ILB",
    },
    "Broughty Ferry": {
        "label": "Broughty Ferry, City of Dundee",
        "latitude": 56.46498,
        "longitude": -2.87731,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/broughty-ferry-lifeboat-station",
        "what3words": "///coach.chop.flat",
        "station_type": "ALB",
    },
    "Buckie": {
        "label": "Buckie, Banffshire",
        "latitude": 57.68087,
        "longitude": -2.95271,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/buckie-lifeboat-station",
        "what3words": "///modern.kidney.romantics",
        "station_type": "ALB",
    },
    "Bude": {
        "label": "Bude, Cornwall",
        "latitude": 50.83073,
        "longitude": -4.55008,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/bude-lifeboat-station",
        "what3words": "///awoke.expect.bathtubs",
        "station_type": "ILB",
    },
    "Bundoran": {
        "label": "Bundoran, Donegal",
        "latitude": 54.47702,
        "longitude": -8.28914,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/bundoran-lifeboat-station",
        "what3words": "///doorway.raising.fans",
        "station_type": "ILB",
    },
    "Burnham-on-Crouch": {
        "label": "Burnham-on-Crouch, Essex",
        "latitude": 51.62918,
        "longitude": 0.80253,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/burnham-on-crouch-lifeboat-station",
        "what3words": "///gushes.regrowth.requires",
        "station_type": "ILB",
    },
    "Burnham-on-Sea": {
        "label": "Burnham-on-Sea, Somerset",
        "latitude": 51.23372,
        "longitude": -2.9972,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/burnham-on-sea-lifeboat-station",
        "what3words": "///cultivation.jump.dynasties",
        "station_type": "ILB",
    },
    "Burry Port": {
        "label": "Burry Port, Dyfed",
        "latitude": 51.67973,
        "longitude": -4.24848,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/burry-port-lifeboat-station",
        "what3words": "///tidal.fingertip.running",
        "station_type": "ILB",
    },
    "Calshot": {
        "label": "Calshot, Hampshire",
        "latitude": 50.82025,
        "longitude": -1.30834,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/calshot-lifeboat-station",
        "what3words": "///squish.attitudes.violin",
        "station_type": "ILB",
    },
    "Campbeltown": {
        "label": "Campbeltown, Argyll and Bute",
        "latitude": 55.42517,
        "longitude": -5.60196,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/campbeltown-lifeboat-station",
        "what3words": "///quieter.breeze.essential",
        "station_type": "ALB",
    },
    "Cardigan": {
        "label": "Cardigan, Dyfed",
        "latitude": 52.10474,
        "longitude": -4.69953,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/cardigan-lifeboat-station",
        "what3words": "///gasping.legwork.stitching",
        "station_type": "ILB",
    },
    "Carrybridge": {
        "label": "Carrybridge, Fermanagh",
        "latitude": 54.28752,
        "longitude": -7.54842,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/carrybridge-lifeboat-station",
        "what3words": "///slant.evolves.taped",
        "station_type": "ILB",
    },
    "Castletownbere": {
        "label": "Castletownbere, Cork",
        "latitude": 51.65209,
        "longitude": -9.90839,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/castletownbere-lifeboat-station",
        "what3words": "///pelt.inundated.strand",
        "station_type": "ALB",
    },
    "Chiswick": {
        "label": "Chiswick, Greater London",
        "latitude": 51.48214,
        "longitude": -0.25158,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/chiswick-lifeboat-station",
        "what3words": "///swan.maps.solo",
        "station_type": "ILB",
    },
    "Clacton-on-Sea": {
        "label": "Clacton-on-Sea, Essex",
        "latitude": 51.78153,
        "longitude": 1.14127,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/clacton-on-sea-lifeboat-station",
        "what3words": "///listed.blockage.standard",
        "station_type": "ILB",
    },
    "Cleethorpes": {
        "label": "Cleethorpes, Lincolnshire",
        "latitude": 53.55697,
        "longitude": -0.0233,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/cleethorpes-lifeboat-station",
        "what3words": "///live.void.dreams",
        "station_type": "ILB",
    },
    "Clifden": {
        "label": "Clifden, Galway",
        "latitude": 53.48616,
        "longitude": -10.05067,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/clifden-lifeboat-station",
        "what3words": "///ballot.philosophers.trinkets",
        "station_type": "ALB",
    },
    "Clogherhead": {
        "label": "Clogherhead, Louth",
        "latitude": 53.78845,
        "longitude": -6.23533,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/clogher-head-lifeboat-station",
        "what3words": "///belong.regrowth.detention",
        "station_type": "ALB",
    },
    "Clovelly": {
        "label": "Clovelly, Devon",
        "latitude": 50.99833,
        "longitude": -4.39757,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/clovelly-lifeboat-station",
        "what3words": "///moods.notch.biked",
        "station_type": "ILB",
    },
    "Conwy": {
        "label": "Conwy, Clwyd",
        "latitude": 53.28094,
        "longitude": -3.82639,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/conwy-lifeboat-station",
        "what3words": "///crisps.feed.juggles",
        "station_type": "ILB",
    },
    "Courtmacsherry Harbour": {
        "label": "Courtmacsherry Harbour, Cork",
        "latitude": 51.63494,
        "longitude": -8.70929,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/courtmacsherry-harbour-lifeboat-station",
        "what3words": "///vintage.librarians.standstill",
        "station_type": "ALB",
    },
    "Courtown": {
        "label": "Courtown, Wexford",
        "latitude": 52.64349,
        "longitude": -6.22583,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/courtown-lifeboat-station",
        "what3words": "///oxygen.refills.piping",
        "station_type": "ILB",
    },
    "Cowes": {
        "label": "Cowes, Isle of Wight",
        "latitude": 50.76473,
        "longitude": -1.29829,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/cowes-lifeboat-station",
        "what3words": "///prance.scooter.emulating",
        "station_type": "ILB",
    },
    "Craster": {
        "label": "Craster, Northumberland",
        "latitude": 55.47262,
        "longitude": -1.59416,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/craster-lifeboat-station",
        "what3words": "///unscathed.glue.leads",
        "station_type": "ILB",
    },
    "Criccieth": {
        "label": "Criccieth, Gwynedd",
        "latitude": 52.91806,
        "longitude": -4.23048,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/criccieth-lifeboat-station",
        "what3words": "///originate.rating.buns",
        "station_type": "ILB",
    },
    "Cromer": {
        "label": "Cromer, Norfolk",
        "latitude": 52.9343,
        "longitude": 1.30163,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/cromer-lifeboat-station",
        "what3words": "///willpower.scan.iceberg",
        "station_type": "ALB",
    },
    "Crosshaven": {
        "label": "Crosshaven, Cork",
        "latitude": 51.80447,
        "longitude": -8.29796,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/crosshaven-lifeboat-station",
        "what3words": "///causal.gravely.respond",
        "station_type": "ILB",
    },
    "Cullercoats": {
        "label": "Cullercoats, Tyne & Wear",
        "latitude": 55.03551,
        "longitude": -1.43205,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/cullercoats-lifeboat-station",
        "what3words": "///gave.debate.storms",
        "station_type": "ILB",
    },
    "Dart": {
        "label": "Dart, Devon",
        "latitude": 50.35474,
        "longitude": -3.57802,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/dart-lifeboat-station",
        "what3words": "///paraded.blindfold.captions",
        "station_type": "ILB",
    },
    "Donaghadee": {
        "label": "Donaghadee, Down",
        "latitude": 54.64343,
        "longitude": -5.53198,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/donaghadee-lifeboat-station",
        "what3words": "///skinny.refusals.width",
        "station_type": "ALB",
    },
    "Douglas": {
        "label": "Douglas, Isle of Man",
        "latitude": 54.14487,
        "longitude": -4.46975,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/douglas-lifeboat-station",
        "what3words": "///hurls.armed.curvy",
        "station_type": "ALB",
    },
    "Dover": {
        "label": "Dover, Kent",
        "latitude": 51.11826,
        "longitude": 1.31068,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/dover-lifeboat-station",
        "what3words": "///belt.ends.removable",
        "station_type": "ALB",
    },
    "Dun Laoghaire": {
        "label": "Dun Laoghaire, Dublin",
        "latitude": 53.2937,
        "longitude": -6.13104,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/dun-laoghaire-lifeboat-station",
        "what3words": "///tribes.discrepancy.direct",
        "station_type": "ALB",
    },
    "Dunbar": {
        "label": "Dunbar, East Lothian",
        "latitude": 56.00504,
        "longitude": -2.51494,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/dunbar-lifeboat-station",
        "what3words": "///trails.caravans.warrior",
        "station_type": "ALB",
    },
    "Dungeness": {
        "label": "Dungeness, Kent",
        "latitude": 50.92648,
        "longitude": 0.97647,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/dungeness-lifeboat-station",
        "what3words": "///lump.arts.wriggled",
        "station_type": "ALB",
    },
    "Dunmore East": {
        "label": "Dunmore East, Waterford",
        "latitude": 52.14706,
        "longitude": -6.99253,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/dunmore-east-lifeboat-station",
        "what3words": "///brother.granite.mistakes",
        "station_type": "ALB",
    },
    "Eastbourne": {
        "label": "Eastbourne, East Sussex",
        "latitude": 50.79112,
        "longitude": 0.32805,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/eastbourne-lifeboat-station",
        "what3words": "///ushering.cashier.popular",
        "station_type": "ALB",
    },
    "Enniskillen": {
        "label": "Enniskillen, Fermanagh",
        "latitude": 54.42249,
        "longitude": -7.68214,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/enniskillen-lifeboat-station",
        "what3words": "///burst.district.adhesive",
        "station_type": "ILB",
    },
    "Exmouth": {
        "label": "Exmouth, Devon",
        "latitude": 50.61105,
        "longitude": -3.39898,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/exmouth-lifeboat-station",
        "what3words": "///wake.pits.pops",
        "station_type": "ALB",
    },
    "Eyemouth": {
        "label": "Eyemouth, Berwickshire",
        "latitude": 55.87218,
        "longitude": -2.08611,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/eyemouth-lifeboat-station",
        "what3words": "///however.woodstove.baker",
        "station_type": "ALB",
    },
    "Falmouth": {
        "label": "Falmouth, Cornwall",
        "latitude": 50.15131,
        "longitude": -5.05911,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/falmouth-lifeboat-station",
        "what3words": "///casual.stops.tidy",
        "station_type": "ALB",
    },
    "Fenit": {
        "label": "Fenit, Kerry",
        "latitude": 52.2717,
        "longitude": -9.86301,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/fenit-lifeboat-station",
        "what3words": "///cartons.qualifications.nurses",
        "station_type": "ALB",
    },
    "Fethard": {
        "label": "Fethard, Wexford",
        "latitude": 52.18776,
        "longitude": -6.8382,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/fethard-lifeboat-station",
        "what3words": "///accustomed.acute.removers",
        "station_type": "ILB",
    },
    "Filey": {
        "label": "Filey, North Yorkshire",
        "latitude": 54.21133,
        "longitude": -0.28339,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/filey-lifeboat-station",
        "what3words": "///domain.ferried.mini",
        "station_type": "ILB",
    },
    "Fishguard": {
        "label": "Fishguard, Dyfed",
        "latitude": 52.0133,
        "longitude": -4.9841,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/fishguard-lifeboat-station",
        "what3words": "///tens.sedated.consented",
        "station_type": "ALB",
    },
    "Flamborough": {
        "label": "Flamborough, East Riding of Yorkshire",
        "latitude": 54.10473,
        "longitude": -0.11898,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/flamborough-lifeboat-station",
        "what3words": "///suits.albatross.madder",
        "station_type": "ILB",
    },
    "Fleetwood": {
        "label": "Fleetwood, Lancashire",
        "latitude": 53.92776,
        "longitude": -3.00653,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/fleetwood-lifeboat-station",
        "what3words": "///shadows.multiples.blanked",
        "station_type": "ALB",
    },
    "Flint": {
        "label": "Flint, Clwyd",
        "latitude": 53.25051,
        "longitude": -3.12847,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/flint-lifeboat-station",
        "what3words": "///robot.purified.irrigated",
        "station_type": "ILB",
    },
    "Fowey": {
        "label": "Fowey, Cornwall",
        "latitude": 50.33873,
        "longitude": -4.63234,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/fowey-lifeboat-station",
        "what3words": "///rectangular.years.recoup",
        "station_type": "ALB",
    },
    "Fraserburgh": {
        "label": "Fraserburgh, Aberdeenshire",
        "latitude": 57.69355,
        "longitude": -2.00281,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/fraserburgh-lifeboat-station",
        "what3words": "///zoomed.tonality.cones",
        "station_type": "ALB",
    },
    "Galway": {
        "label": "Galway, Galway",
        "latitude": 53.26914,
        "longitude": -9.04688,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/galway-lifeboat-station",
        "what3words": "///punchy.hill.police",
        "station_type": "ILB",
    },
    "Girvan": {
        "label": "Girvan, Ayrshire and Arran",
        "latitude": 55.24338,
        "longitude": -4.85764,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/girvan-lifeboat-station",
        "what3words": "///fries.recliner.confusion",
        "station_type": "ALB",
    },
    "Gravesend": {
        "label": "Gravesend, Kent",
        "latitude": 51.44527,
        "longitude": 0.37455,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/gravesend-lifeboat-station",
        "what3words": "///actors.picked.fallen",
        "station_type": "ILB",
    },
    "Great Yarmouth and Gorleston": {
        "label": "Great Yarmouth and Gorleston, Norfolk",
        "latitude": 52.57522,
        "longitude": 1.73192,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/great-yarmouth-and-gorleston-lifeboat-station",
        "what3words": "///lights.early.dance",
        "station_type": "ALB",
    },
    "Happisburgh": {
        "label": "Happisburgh, Norfolk",
        "latitude": 52.8133,
        "longitude": 1.5562,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/happisburgh-lifeboat-station",
        "what3words": "///victor.fewer.sprains",
        "station_type": "ILB",
    },
    "Hartlepool": {
        "label": "Hartlepool, Durham",
        "latitude": 54.69484,
        "longitude": -1.19104,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/hartlepool-lifeboat-station",
        "what3words": "///trio.basis.fishery",
        "station_type": "ALB",
    },
    "Harwich": {
        "label": "Harwich, Essex",
        "latitude": 51.9486,
        "longitude": 1.28712,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/harwich-lifeboat-station",
        "what3words": "///expectant.petition.apes",
        "station_type": "ALB",
    },
    "Hastings": {
        "label": "Hastings, East Sussex",
        "latitude": 50.85508,
        "longitude": 0.59172,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/hastings-lifeboat-station",
        "what3words": "///unions.fully.foods",
        "station_type": "ALB",
    },
    "Hayling Island": {
        "label": "Hayling Island, Hampshire",
        "latitude": 50.78171,
        "longitude": -0.93677,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/hayling-island-lifeboat-station",
        "what3words": "///list.reflector.credited",
        "station_type": "ILB",
    },
    "Helensburgh": {
        "label": "Helensburgh, Dunbartonshire",
        "latitude": 56.01305,
        "longitude": -4.77342,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/helensburgh-lifeboat-station",
        "what3words": "///massaging.airtime.laces",
        "station_type": "ILB",
    },
    "Helvick Head": {
        "label": "Helvick Head, Waterford",
        "latitude": 52.05461,
        "longitude": -7.54407,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/helvick-head-lifeboat-station",
        "what3words": "///upswept.guitar.bolstering",
        "station_type": "ILB",
    },
    "Holyhead": {
        "label": "Holyhead, Gwynedd",
        "latitude": 53.31803,
        "longitude": -4.64184,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/holyhead-lifeboat-station",
        "what3words": "///bank.quietest.steaming",
        "station_type": "ALB",
    },
    "Horton and Port Eynon": {
        "label": "Horton and Port Eynon, West Glamorgan",
        "latitude": 51.5483,
        "longitude": -4.2011,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/horton-and-port-eynon-lifeboat-station",
        "what3words": "///waking.scrambles.darkens",
        "station_type": "ILB",
    },
    "Howth": {
        "label": "Howth, Dublin",
        "latitude": 53.38961,
        "longitude": -6.06827,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/howth-lifeboat-station",
        "what3words": "///gunk.appealing.mortgages",
        "station_type": "ALB",
    },
    "Hoylake": {
        "label": "Hoylake, Merseyside",
        "latitude": 53.39919,
        "longitude": -3.17751,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/hoylake-lifeboat-station",
        "what3words": "///loaded.sparrows.panther",
        "station_type": "ALB",
    },
    "Humber": {
        "label": "Humber, East Riding of Yorkshire",
        "latitude": 53.58115,
        "longitude": -0.06624,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/humber-lifeboat-station",
        "what3words": "///defers.imparting.zealous",
        "station_type": "ALB",
    },
    "Hunstanton": {
        "label": "Hunstanton, Norfolk",
        "latitude": 52.95406,
        "longitude": 0.50268,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/hunstanton-lifeboat-station",
        "what3words": "///spells.yacht.nothing",
        "station_type": "ILB",
    },
    "Ilfracombe": {
        "label": "Ilfracombe, Devon",
        "latitude": 51.20966,
        "longitude": -4.11612,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/ilfracombe-lifeboat-station",
        "what3words": "///dash.imitate.hardback",
        "station_type": "ALB",
    },
    "Invergordon": {
        "label": "Invergordon, Ross and Cromarty",
        "latitude": 57.68655,
        "longitude": -4.16741,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/invergordon-lifeboat-station",
        "what3words": "///vowel.convinces.doors",
        "station_type": "ALB",
    },
    "Islay": {
        "label": "Islay, Argyll and Bute",
        "latitude": 55.84852,
        "longitude": -6.10506,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/islay-lifeboat-station",
        "what3words": "///indicated.march.defeat",
        "station_type": "ALB",
    },
    "Kessock": {
        "label": "Kessock, Ross and Cromarty",
        "latitude": 57.50094,
        "longitude": -4.23466,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kessock-lifeboat-station",
        "what3words": "///verb.regret.dignity",
        "station_type": "ILB",
    },
    "Kilkeel": {
        "label": "Kilkeel, Down",
        "latitude": 54.05849,
        "longitude": -5.99019,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kilkeel-lifeboat-station",
        "what3words": "///dial.typified.retraced",
        "station_type": "ILB",
    },
    "Kilmore Quay": {
        "label": "Kilmore Quay, Wexford",
        "latitude": 52.17328,
        "longitude": -6.58972,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kilmore-quay-lifeboat-station",
        "what3words": "///tech.kettles.sagged",
        "station_type": "ALB",
    },
    "Kilrush": {
        "label": "Kilrush, Clare",
        "latitude": 52.62997,
        "longitude": -9.50055,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kilrush-lifeboat-station",
        "what3words": "///outsell.sunlit.astronauts",
        "station_type": "ILB",
    },
    "Kinghorn": {
        "label": "Kinghorn, Fife",
        "latitude": 56.0686,
        "longitude": -3.17407,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kinghorn-lifeboat-station",
        "what3words": "///slicer.nicer.activity",
        "station_type": "ILB",
    },
    "Kinsale": {
        "label": "Kinsale, Cork",
        "latitude": 51.70006,
        "longitude": -8.5178,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kinsale-lifeboat-station",
        "what3words": "///qualifier.accountants.outline",
        "station_type": "ILB",
    },
    "Kippford": {
        "label": "Kippford, The Stewartry of Kirkcudbright",
        "latitude": 54.8765,
        "longitude": -3.8135,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kippford-lifeboat-station",
        "what3words": "///cloak.funds.culling",
        "station_type": "ILB",
    },
    "Kirkcudbright": {
        "label": "Kirkcudbright, The Stewartry of Kirkcudbright",
        "latitude": 54.79467,
        "longitude": -4.06246,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kirkcudbright-lifeboat-station",
        "what3words": "///vaulting.diet.factually",
        "station_type": "ILB",
    },
    "Kirkwall": {
        "label": "Kirkwall, Orkney",
        "latitude": 58.98543,
        "longitude": -2.96037,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kirkwall-lifeboat-station",
        "what3words": "///slanting.reviews.lobbed",
        "station_type": "ALB",
    },
    "Kyle of Lochalsh": {
        "label": "Kyle of Lochalsh, Ross and Cromarty",
        "latitude": 57.28016,
        "longitude": -5.7147,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/kyle-of-lochalsh-lifeboat-station",
        "what3words": "///speak.forensic.librarian",
        "station_type": "ILB",
    },
    "Largs": {
        "label": "Largs, Ayrshire and Arran",
        "latitude": 55.80015,
        "longitude": -4.87068,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/largs-lifeboat-station",
        "what3words": "///strategy.comet.birdcage",
        "station_type": "ILB",
    },
    "Larne": {
        "label": "Larne, Antrim",
        "latitude": 54.84673,
        "longitude": -5.80013,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/larne-lifeboat-station",
        "what3words": "///happily.lecturers.cheat",
        "station_type": "ALB",
    },
    "Lerwick": {
        "label": "Lerwick, Shetland",
        "latitude": 60.15324,
        "longitude": -1.14059,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lerwick-lifeboat-station",
        "what3words": "///clan.panther.direction",
        "station_type": "ALB",
    },
    "Leverburgh": {
        "label": "Leverburgh, Western Isles",
        "latitude": 57.76781,
        "longitude": -7.02378,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/leverburgh-lifeboat-station",
        "what3words": "///blueberry.sour.dinner",
        "station_type": "ILB",
    },
    "Little and Broad Haven": {
        "label": "Little and Broad Haven, Dyfed",
        "latitude": 51.77316,
        "longitude": -5.10715,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/little-and-broad-haven-lifeboat-station",
        "what3words": "///encourage.cringes.giving",
        "station_type": "ILB",
    },
    "Littlehampton": {
        "label": "Littlehampton, West Sussex",
        "latitude": 50.80802,
        "longitude": -0.54454,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/littlehampton-lifeboat-station",
        "what3words": "///shield.tree.neon",
        "station_type": "ILB",
    },
    "Littlestone-on-Sea": {
        "label": "Littlestone-on-Sea, Kent",
        "latitude": 50.97462,
        "longitude": 0.96559,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/littlestone-on-sea-lifeboat-station",
        "what3words": "///scrapped.slyly.ashes",
        "station_type": "ILB",
    },
    "Llandudno": {
        "label": "Llandudno, Clwyd",
        "latitude": 53.32288,
        "longitude": -3.80225,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/llandudno-lifeboat-station",
        "what3words": "///upset.fell.populate",
        "station_type": "ALB",
    },
    "Loch Ness": {
        "label": "Loch Ness, Inverness",
        "latitude": 57.33673,
        "longitude": -4.44444,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/loch-ness-lifeboat-station",
        "what3words": "///slams.increased.frock",
        "station_type": "ILB",
    },
    "Lochinver": {
        "label": "Lochinver, Sutherland",
        "latitude": 58.14679,
        "longitude": -5.2476,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lochinver-lifeboat-station",
        "what3words": "///pasta.repair.toasters",
        "station_type": "ALB",
    },
    "Longhope": {
        "label": "Longhope, Orkney",
        "latitude": 58.80058,
        "longitude": -3.20692,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/longhope-lifeboat-station",
        "what3words": "///wiser.podcast.coverings",
        "station_type": "ALB",
    },
    "Looe": {
        "label": "Looe, Cornwall",
        "latitude": 50.35197,
        "longitude": -4.45315,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/looe-lifeboat-station",
        "what3words": "///purple.riverbank.reminder",
        "station_type": "ILB",
    },
    "Lough Derg": {
        "label": "Lough Derg, Tipperary",
        "latitude": 52.92608,
        "longitude": -8.27563,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lough-derg-lifeboat-station",
        "what3words": "///clubs.lazed.necessary",
        "station_type": "ILB",
    },
    "Lough Ree": {
        "label": "Lough Ree, Westmeath",
        "latitude": 53.46405,
        "longitude": -7.92837,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lough-ree-lifeboat-station",
        "what3words": "///cape.faculty.genre",
        "station_type": "ILB",
    },
    "Lough Swilly": {
        "label": "Lough Swilly, Donegal",
        "latitude": 55.1409,
        "longitude": -7.47343,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lough-swilly-lifeboat-station",
        "what3words": "///herald.viewers.contest",
        "station_type": "ALB",
    },
    "Lowestoft": {
        "label": "Lowestoft, Suffolk",
        "latitude": 52.47167,
        "longitude": 1.75299,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lowestoft-lifeboat-station",
        "what3words": "///ever.unit.during",
        "station_type": "ALB",
    },
    "Lyme Regis": {
        "label": "Lyme Regis, Dorset",
        "latitude": 50.72044,
        "longitude": -2.93902,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lyme-regis-lifeboat-station",
        "what3words": "///successor.from.inert",
        "station_type": "ILB",
    },
    "Lymington": {
        "label": "Lymington, Hampshire",
        "latitude": 50.75381,
        "longitude": -1.52922,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lymington-lifeboat-station",
        "what3words": "///chops.crockery.gathers",
        "station_type": "ILB",
    },
    "Lytham St Annes": {
        "label": "Lytham St Annes, Lancashire",
        "latitude": 53.7467,
        "longitude": -3.0326,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/lytham-st-annes-lifeboat-station",
        "what3words": "///clasps.grills.breeze",
        "station_type": "ALB",
    },
    "Mablethorpe": {
        "label": "Mablethorpe, Lincolnshire",
        "latitude": 53.3408,
        "longitude": 0.2659,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/mablethorpe-lifeboat-station",
        "what3words": "///shakes.signal.narrowest",
        "station_type": "ILB",
    },
    "Macduff": {
        "label": "Macduff, Banffshire",
        "latitude": 57.67273,
        "longitude": -2.49433,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/macduff-lifeboat-station",
        "what3words": "///weekend.rolled.enchanted",
        "station_type": "ILB",
    },
    "Mallaig": {
        "label": "Mallaig, Inverness",
        "latitude": 57.00629,
        "longitude": -5.82901,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/mallaig-lifeboat-station",
        "what3words": "///protest.consonant.brass",
        "station_type": "ALB",
    },
    "Margate": {
        "label": "Margate, Kent",
        "latitude": 51.39164,
        "longitude": 1.38275,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/margate-lifeboat-station",
        "what3words": "///spun.head.clots",
        "station_type": "ILB",
    },
    "Minehead": {
        "label": "Minehead, Somerset",
        "latitude": 51.21402,
        "longitude": -3.47531,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/minehead-lifeboat-station",
        "what3words": "///forklift.refilled.packing",
        "station_type": "ILB",
    },
    "Moelfre": {
        "label": "Moelfre, Gwynedd",
        "latitude": 53.35466,
        "longitude": -4.23196,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/moelfre-lifeboat-station",
        "what3words": "///parrot.refrained.succeed",
        "station_type": "ALB",
    },
    "Montrose": {
        "label": "Montrose, Angus",
        "latitude": 56.7068,
        "longitude": -2.4721,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/montrose-lifeboat-station",
        "what3words": "///hilltop.mingles.suggested",
        "station_type": "ALB",
    },
    "Morecambe": {
        "label": "Morecambe, Lancashire",
        "latitude": 54.07511,
        "longitude": -2.86361,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/morecambe-lifeboat-station",
        "what3words": "///beast.yard.brief",
        "station_type": "ILB",
    },
    "Mudeford": {
        "label": "Mudeford, Dorset",
        "latitude": 50.72429,
        "longitude": -1.74227,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/mudeford-lifeboat-station",
        "what3words": "///empire.twins.barn",
        "station_type": "ILB",
    },
    "New Brighton": {
        "label": "New Brighton, Merseyside",
        "latitude": 53.43945,
        "longitude": -3.04727,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/new-brighton-lifeboat-station",
        "what3words": "///drops.forest.script",
        "station_type": "ILB",
    },
    "New Quay (Ceredigion)": {
        "label": "New Quay (Ceredigion), Dyfed",
        "latitude": 52.21351,
        "longitude": -4.35762,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/new-quay-lifeboat-station",
        "what3words": "///scans.howler.twee",
        "station_type": "ALB",
    },
    "Newbiggin": {
        "label": "Newbiggin, Northumberland",
        "latitude": 55.18592,
        "longitude": -1.50659,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/newbiggin-lifeboat-station",
        "what3words": "///whips.auctioned.notebook",
        "station_type": "ILB",
    },
    "Newcastle (Co Down)": {
        "label": "Newcastle (Co Down), Down",
        "latitude": 54.19796,
        "longitude": -5.88715,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/newcastle-lifeboat-station",
        "what3words": "///field.flotation.oils",
        "station_type": "ALB",
    },
    "Newhaven": {
        "label": "Newhaven, East Sussex",
        "latitude": 50.78854,
        "longitude": 0.05372,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/newhaven-lifeboat-station",
        "what3words": "///songbook.amuse.hushed",
        "station_type": "ALB",
    },
    "Newquay (Cornwall)": {
        "label": "Newquay (Cornwall), Cornwall",
        "latitude": 50.41648,
        "longitude": -5.08729,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/newquay-lifeboat-station",
        "what3words": "///blip.gossip.inkjet",
        "station_type": "ILB",
    },
    "North Berwick": {
        "label": "North Berwick, East Lothian",
        "latitude": 56.06033,
        "longitude": -2.71764,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/north-berwick-lifeboat-station",
        "what3words": "///arise.simmer.smashes",
        "station_type": "ILB",
    },
    "Oban": {
        "label": "Oban, Argyll and Bute",
        "latitude": 56.41103,
        "longitude": -5.47962,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/oban-lifeboat-station",
        "what3words": "///corded.woodstove.marketing",
        "station_type": "ALB",
    },
    "Padstow": {
        "label": "Padstow, Cornwall",
        "latitude": 50.54903,
        "longitude": -5.02173,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/padstow-lifeboat-station",
        "what3words": "///crowds.ranks.newlywed",
        "station_type": "ALB",
    },
    "Peel": {
        "label": "Peel, Isle of Man",
        "latitude": 54.2271,
        "longitude": -4.69805,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/peel-lifeboat-station",
        "what3words": "///thunder.gave.upon",
        "station_type": "ALB",
    },
    "Penarth": {
        "label": "Penarth, South Glamorgan",
        "latitude": 51.43256,
        "longitude": -3.16902,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/penarth-lifeboat-station",
        "what3words": "///angle.dent.shine",
        "station_type": "ILB",
    },
    "Penlee": {
        "label": "Penlee, Cornwall",
        "latitude": 50.10393,
        "longitude": -5.54872,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/penlee-lifeboat-station",
        "what3words": "///suitably.burden.pilots",
        "station_type": "ALB",
    },
    "Peterhead": {
        "label": "Peterhead, Aberdeenshire",
        "latitude": 57.50308,
        "longitude": -1.77463,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/peterhead-lifeboat-station",
        "what3words": "///hiring.spurned.retraced",
        "station_type": "ALB",
    },
    "Plymouth": {
        "label": "Plymouth, Devon",
        "latitude": 50.36304,
        "longitude": -4.15038,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/plymouth-lifeboat-station",
        "what3words": "///mile.films.action",
        "station_type": "ALB",
    },
    "Poole": {
        "label": "Poole, Dorset",
        "latitude": 50.71269,
        "longitude": -1.99197,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/poole-lifeboat-station",
        "what3words": "///scarf.insist.nails",
        "station_type": "ILB",
    },
    "Port Erin": {
        "label": "Port Erin, Isle of Man",
        "latitude": 54.08519,
        "longitude": -4.76801,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/port-erin-lifeboat-station",
        "what3words": "///influential.kittens.unexplored",
        "station_type": "ILB",
    },
    "Port Isaac": {
        "label": "Port Isaac, Cornwall",
        "latitude": 50.59201,
        "longitude": -4.83199,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/port-isaac-lifeboat-station",
        "what3words": "///hems.diver.ironic",
        "station_type": "ILB",
    },
    "Port St Mary": {
        "label": "Port St Mary, Isle of Man",
        "latitude": 54.07045,
        "longitude": -4.7345,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/port-st-mary-lifeboat-station",
        "what3words": "///differ.ashes.recollection",
        "station_type": "ALB",
    },
    "Port Talbot": {
        "label": "Port Talbot, West Glamorgan",
        "latitude": 51.59354,
        "longitude": -3.81686,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/port-talbot-lifeboat-station",
        "what3words": "///overnight.brief.retail",
        "station_type": "ILB",
    },
    "Portaferry": {
        "label": "Portaferry, Down",
        "latitude": 54.38089,
        "longitude": -5.54929,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/portaferry-lifeboat-station",
        "what3words": "///crouching.discrepancy.darker",
        "station_type": "ILB",
    },
    "Porthcawl": {
        "label": "Porthcawl, Mid Glamorgan",
        "latitude": 51.47415,
        "longitude": -3.70202,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/porthcawl-lifeboat-station",
        "what3words": "///butterfly.moment.fidgeted",
        "station_type": "ILB",
    },
    "Porthdinllaen": {
        "label": "Porthdinllaen, Gwynedd",
        "latitude": 52.94699,
        "longitude": -4.56472,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/porthdinllaen-lifeboat-station",
        "what3words": "///obstinate.splat.sooner",
        "station_type": "ALB",
    },
    "Portishead": {
        "label": "Portishead, Somerset",
        "latitude": 51.49389,
        "longitude": -2.75697,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/portishead-lifeboat-station",
        "what3words": "///chief.roadmap.typically",
        "station_type": "ILB",
    },
    "Portpatrick": {
        "label": "Portpatrick, Wigtown",
        "latitude": 54.84193,
        "longitude": -5.11992,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/portpatrick-lifeboat-station",
        "what3words": "///ladders.safe.pampered",
        "station_type": "ALB",
    },
    "Portree": {
        "label": "Portree, Ross and Cromarty",
        "latitude": 57.41079,
        "longitude": -6.19002,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/portree-lifeboat-station",
        "what3words": "///observer.booms.daily",
        "station_type": "ALB",
    },
    "Portrush": {
        "label": "Portrush, Antrim",
        "latitude": 55.20681,
        "longitude": -6.65661,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/portrush-lifeboat-station",
        "what3words": "///encodes.funny.enacts",
        "station_type": "ALB",
    },
    "Portsmouth": {
        "label": "Portsmouth, Hampshire",
        "latitude": 50.79537,
        "longitude": -1.02986,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/portsmouth-lifeboat-station",
        "what3words": "///nation.fast.healers",
        "station_type": "ILB",
    },
    "Pwllheli": {
        "label": "Pwllheli, Gwynedd",
        "latitude": 52.88687,
        "longitude": -4.40387,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/pwllheli-lifeboat-station",
        "what3words": "///pimples.crown.browsers",
        "station_type": "ALB",
    },
    "Queensferry": {
        "label": "Queensferry, City of Edinburgh",
        "latitude": 55.99063,
        "longitude": -3.38526,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/queensferry-lifeboat-station",
        "what3words": "///nylon.swim.ballpoint",
        "station_type": "ILB",
    },
    "Ramsey": {
        "label": "Ramsey, Isle of Man",
        "latitude": 54.32256,
        "longitude": -4.37841,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/ramsey-lifeboat-station",
        "what3words": "///crucially.inch.wrangle",
        "station_type": "ALB",
    },
    "Ramsgate": {
        "label": "Ramsgate, Kent",
        "latitude": 51.32899,
        "longitude": 1.4198,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/ramsgate-lifeboat-station",
        "what3words": "///bottom.create.menu",
        "station_type": "ALB",
    },
    "Red Bay": {
        "label": "Red Bay, Antrim",
        "latitude": 55.075,
        "longitude": -6.05346,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/red-bay-lifeboat-station",
        "what3words": "///appealing.submitted.polar",
        "station_type": "ALB",
    },
    "Redcar": {
        "label": "Redcar, North Yorkshire",
        "latitude": 54.61857,
        "longitude": -1.0637,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/redcar-lifeboat-station",
        "what3words": "///encounter.tiles.tulip",
        "station_type": "ILB",
    },
    "Rhyl": {
        "label": "Rhyl, Clwyd",
        "latitude": 53.32505,
        "longitude": -3.48889,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/rhyl-lifeboat-station",
        "what3words": "///cone.feels.dads",
        "station_type": "ALB",
    },
    "Rock": {
        "label": "Rock, Cornwall",
        "latitude": 50.54462,
        "longitude": -4.92449,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/rock-lifeboat-station",
        "what3words": "///flaunting.comb.opposites",
        "station_type": "ILB",
    },
    "Rosslare Harbour": {
        "label": "Rosslare Harbour, Wexford",
        "latitude": 52.25398,
        "longitude": -6.33574,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/rosslare-harbour-lifeboat-station",
        "what3words": "///ravish.orientation.senseless",
        "station_type": "ALB",
    },
    "Rye Harbour": {
        "label": "Rye Harbour, East Sussex",
        "latitude": 50.93847,
        "longitude": 0.76405,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/rye-harbour-lifeboat-station",
        "what3words": "///pats.discount.clip",
        "station_type": "ILB",
    },
    "Salcombe": {
        "label": "Salcombe, Devon",
        "latitude": 50.23866,
        "longitude": -3.76666,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/salcombe-lifeboat-station",
        "what3words": "///bleach.stooping.complies",
        "station_type": "ALB",
    },
    "Scarborough": {
        "label": "Scarborough, North Yorkshire",
        "latitude": 54.28341,
        "longitude": -0.39309,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/scarborough-lifeboat-station",
        "what3words": "///scam.pinch.drill",
        "station_type": "ALB",
    },
    "Seahouses": {
        "label": "Seahouses, Northumberland",
        "latitude": 55.58289,
        "longitude": -1.65403,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/seahouses-lifeboat-station",
        "what3words": "///slimming.embers.cargo",
        "station_type": "ALB",
    },
    "Selsey": {
        "label": "Selsey, West Sussex",
        "latitude": 50.7282,
        "longitude": -0.77994,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/selsey-lifeboat-station",
        "what3words": "///snowmen.aimlessly.rent",
        "station_type": "ALB",
    },
    "Sennen Cove": {
        "label": "Sennen Cove, Cornwall",
        "latitude": 50.07793,
        "longitude": -5.7037,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/sennen-cove-lifeboat-station",
        "what3words": "///recliner.gravest.zone",
        "station_type": "ALB",
    },
    "Sheerness": {
        "label": "Sheerness, Kent",
        "latitude": 51.4456,
        "longitude": 0.74456,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/sheerness-lifeboat-station",
        "what3words": "///eyebrows.fulfilled.guardian",
        "station_type": "ALB",
    },
    "Sheringham": {
        "label": "Sheringham, Norfolk",
        "latitude": 52.94596,
        "longitude": 1.20263,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/sheringham-lifeboat-station",
        "what3words": "///javelin.arose.trying",
        "station_type": "ILB",
    },
    "Shoreham Harbour": {
        "label": "Shoreham Harbour, West Sussex",
        "latitude": 50.83037,
        "longitude": -0.24895,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/shoreham-harbour-lifeboat-station",
        "what3words": "///saving.flags.wiser",
        "station_type": "ALB",
    },
    "Silloth": {
        "label": "Silloth, Cumbria",
        "latitude": 54.87002,
        "longitude": -3.39317,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/silloth-lifeboat-station",
        "what3words": "///eternally.envoy.food",
        "station_type": "ILB",
    },
    "Skegness": {
        "label": "Skegness, Lincolnshire",
        "latitude": 53.1418,
        "longitude": 0.34676,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/skegness-lifeboat-station",
        "what3words": "///reply.stale.march",
        "station_type": "ALB",
    },
    "Skerries": {
        "label": "Skerries, Dublin",
        "latitude": 53.58583,
        "longitude": -6.10565,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/skerries-lifeboat-station",
        "what3words": "///iterative.lasses.lifestyle",
        "station_type": "ILB",
    },
    "Sligo Bay": {
        "label": "Sligo Bay, Sligo",
        "latitude": 54.30507,
        "longitude": -8.56791,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/sligo-bay-lifeboat-station",
        "what3words": "///unaffected.reasons.prospects",
        "station_type": "ILB",
    },
    "Southend-on-Sea": {
        "label": "Southend-on-Sea, Essex",
        "latitude": 51.53242,
        "longitude": 0.71635,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/southend-on-sea-lifeboat-station",
        "what3words": "///park.door.candy",
        "station_type": "ILB",
    },
    "Southwold": {
        "label": "Southwold, Suffolk",
        "latitude": 52.31496,
        "longitude": 1.67247,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/southwold-lifeboat-station",
        "what3words": "///objecting.patch.flukes",
        "station_type": "ILB",
    },
    "St Agnes": {
        "label": "St Agnes, Cornwall",
        "latitude": 50.31924,
        "longitude": -5.20183,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-agnes-lifeboat-station",
        "what3words": "///shield.culminate.inch",
        "station_type": "ILB",
    },
    "St Bees": {
        "label": "St Bees, Cumbria",
        "latitude": 54.4911,
        "longitude": -3.60656,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-bees-lifeboat-station",
        "what3words": "///cashiers.elastic.aliens",
        "station_type": "ILB",
    },
    "St Catherine": {
        "label": "St Catherine, Channel Isles",
        "latitude": 49.21793,
        "longitude": -2.03017,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-catherine-lifeboat-station",
        "what3words": "///hairbrush.overall.strand",
        "station_type": "ILB",
    },
    "St Davids": {
        "label": "St Davids, Dyfed",
        "latitude": 51.87859,
        "longitude": -5.30905,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-davids-lifeboat-station",
        "what3words": "///roaring.metro.whiplash",
        "station_type": "ALB",
    },
    "St Helier": {
        "label": "St Helier, Channel Isles",
        "latitude": 49.18067,
        "longitude": -2.11303,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-helier-lifeboat-station",
        "what3words": "///other.saga.stays",
        "station_type": "ALB",
    },
    "St Ives": {
        "label": "St Ives, Cornwall",
        "latitude": 50.21274,
        "longitude": -5.47953,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-ives-lifeboat-station",
        "what3words": "///chief.state.flashback",
        "station_type": "ALB",
    },
    "St Mary's": {
        "label": "St Mary's, Cornwall",
        "latitude": 49.91686,
        "longitude": -6.31167,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-marys-lifeboat-station",
        "what3words": "///woodstove.luck.flows",
        "station_type": "ALB",
    },
    "St Peter Port": {
        "label": "St Peter Port, Channel Isles",
        "latitude": 49.45797,
        "longitude": -2.52986,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/st-peter-port-lifeboat-station",
        "what3words": "///light.appealed.credible",
        "station_type": "ALB",
    },
    "Staithes and Runswick": {
        "label": "Staithes and Runswick, North Yorkshire",
        "latitude": 54.55979,
        "longitude": -0.79177,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/staithes-and-runswick-lifeboat-station",
        "what3words": "///crumples.redeemed.cork",
        "station_type": "ILB",
    },
    "Stonehaven": {
        "label": "Stonehaven, Kincardineshire",
        "latitude": 56.96107,
        "longitude": -2.20273,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/stonehaven-lifeboat-station",
        "what3words": "///steaming.tentacles.aquatics",
        "station_type": "ILB",
    },
    "Stornoway": {
        "label": "Stornoway, Western Isles",
        "latitude": 58.21006,
        "longitude": -6.38904,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/stornoway-lifeboat-station",
        "what3words": "///mouse.converter.purest",
        "station_type": "ALB",
    },
    "Stranraer": {
        "label": "Stranraer, Wigtown",
        "latitude": 54.90817,
        "longitude": -5.03522,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/stranraer-lifeboat-station",
        "what3words": "///difficult.birthdays.snippets",
        "station_type": "ILB",
    },
    "Stromness": {
        "label": "Stromness, Orkney",
        "latitude": 58.96334,
        "longitude": -3.29769,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/stromness-lifeboat-station",
        "what3words": "///detective.income.shack",
        "station_type": "ALB",
    },
    "Sunderland": {
        "label": "Sunderland, Tyne & Wear",
        "latitude": 54.92049,
        "longitude": -1.36444,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/sunderland-lifeboat-station",
        "what3words": "///income.builds.oiled",
        "station_type": "ILB",
    },
    "Swanage": {
        "label": "Swanage, Dorset",
        "latitude": 50.60729,
        "longitude": -1.94666,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/swanage-lifeboat-station",
        "what3words": "///answers.dabbled.reassured",
        "station_type": "ALB",
    },
    "Teddington": {
        "label": "Teddington, Greater London",
        "latitude": 51.43085,
        "longitude": -0.32572,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/teddington-lifeboat-station",
        "what3words": "///entry.assist.sums",
        "station_type": "ILB",
    },
    "Teignmouth": {
        "label": "Teignmouth, Devon",
        "latitude": 50.54216,
        "longitude": -3.49783,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/teignmouth-lifeboat-station",
        "what3words": "///riding.grow.collapsed",
        "station_type": "ILB",
    },
    "Tenby": {
        "label": "Tenby, Dyfed",
        "latitude": 51.67302,
        "longitude": -4.69382,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/tenby-lifeboat-station",
        "what3words": "///frames.realm.happier",
        "station_type": "ALB",
    },
    "The Lizard": {
        "label": "The Lizard, Cornwall",
        "latitude": 49.96951,
        "longitude": -5.18705,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/the-lizard-lifeboat-station",
        "what3words": "///snores.awakening.caressed",
        "station_type": "ALB",
    },
    "The Mumbles": {
        "label": "The Mumbles, West Glamorgan",
        "latitude": 51.56985,
        "longitude": -3.97417,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/the-mumbles-lifeboat-station",
        "what3words": "///clusters.bootleg.handyman",
        "station_type": "ALB",
    },
    "Thurso": {
        "label": "Thurso, Caithness",
        "latitude": 58.61208,
        "longitude": -3.54693,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/thurso-lifeboat-station",
        "what3words": "///hobby.microchip.diggers",
        "station_type": "ALB",
    },
    "Tighnabruaich": {
        "label": "Tighnabruaich, Argyll and Bute",
        "latitude": 55.90673,
        "longitude": -5.23264,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/tighnabruaich-lifeboat-station",
        "what3words": "///denim.winners.ramps",
        "station_type": "ILB",
    },
    "Tobermory": {
        "label": "Tobermory, Argyll and Bute",
        "latitude": 56.62327,
        "longitude": -6.06438,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/tobermory-lifeboat-station",
        "what3words": "///national.circles.blackmail",
        "station_type": "ALB",
    },
    "Torbay": {
        "label": "Torbay, Devon",
        "latitude": 50.39915,
        "longitude": -3.50549,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/torbay-lifeboat-station",
        "what3words": "///plug.revamped.town",
        "station_type": "ALB",
    },
    "Tower": {
        "label": "Tower, Greater London",
        "latitude": 51.50997,
        "longitude": -0.11737,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/tower-lifeboat-station",
        "what3words": "///either.polite.beard",
        "station_type": "ILB",
    },
    "Tramore": {
        "label": "Tramore, Waterford",
        "latitude": 52.15411,
        "longitude": -7.16057,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/tramore-lifeboat-station",
        "what3words": "///prom.lightly.undamaged",
        "station_type": "ILB",
    },
    "Trearddur Bay": {
        "label": "Trearddur Bay, Gwynedd",
        "latitude": 53.28065,
        "longitude": -4.61976,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/trearddur-bay-lifeboat-station",
        "what3words": "///attend.blown.hits",
        "station_type": "ILB",
    },
    "Troon": {
        "label": "Troon, Ayrshire and Arran",
        "latitude": 55.54812,
        "longitude": -4.68141,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/troon-lifeboat-station",
        "what3words": "///caressing.centuries.summit",
        "station_type": "ALB",
    },
    "Tynemouth": {
        "label": "Tynemouth, Tyne & Wear",
        "latitude": 55.00917,
        "longitude": -1.4329,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/tynemouth-lifeboat-station",
        "what3words": "///deeper.thanks.pigs",
        "station_type": "ALB",
    },
    "Union Hall": {
        "label": "Union Hall, Cork",
        "latitude": 51.55871,
        "longitude": -9.13395,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/union-hall-lifeboat-station",
        "what3words": "///bakery.invincible.seabird",
        "station_type": "ILB",
    },
    "Valentia": {
        "label": "Valentia, Kerry",
        "latitude": 51.92697,
        "longitude": -10.28819,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/valentia-lifeboat-station",
        "what3words": "///cased.engraving.lushly",
        "station_type": "ALB",
    },
    "Walmer": {
        "label": "Walmer, Kent",
        "latitude": 51.21354,
        "longitude": 1.40304,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/walmer-lifeboat-station",
        "what3words": "///trim.bath.themes",
        "station_type": "ILB",
    },
    "Walton and Frinton": {
        "label": "Walton and Frinton, Essex",
        "latitude": 51.84726,
        "longitude": 1.27117,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/walton-and-frinton-lifeboat-station",
        "what3words": "///into.lighters.trombone",
        "station_type": "ALB",
    },
    "Wells": {
        "label": "Wells, Norfolk",
        "latitude": 52.97298,
        "longitude": 0.85176,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/wells-lifeboat-station",
        "what3words": "///tadpole.jeep.reassured",
        "station_type": "ALB",
    },
    "West Kirby": {
        "label": "West Kirby, Merseyside",
        "latitude": 53.36606,
        "longitude": -3.18234,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/west-kirby-lifeboat-station",
        "what3words": "///curtains.scream.dripping",
        "station_type": "ILB",
    },
    "West Mersea": {
        "label": "West Mersea, Essex",
        "latitude": 51.78032,
        "longitude": 0.89877,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/west-mersea-lifeboat-station",
        "what3words": "///tucked.winning.helpless",
        "station_type": "ILB",
    },
    "Weston-Super-Mare": {
        "label": "Weston-Super-Mare, Somerset",
        "latitude": 51.35225,
        "longitude": -2.98818,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/weston-super-mare-lifeboat-station",
        "what3words": "///green.feeds.long",
        "station_type": "ILB",
    },
    "Wexford": {
        "label": "Wexford, Wexford",
        "latitude": 52.34187,
        "longitude": -6.4617,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/wexford-lifeboat-station",
        "what3words": "///dogfish.closing.befits",
        "station_type": "ILB",
    },
    "Weymouth": {
        "label": "Weymouth, Dorset",
        "latitude": 50.60724,
        "longitude": -2.45016,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/weymouth-lifeboat-station",
        "what3words": "///cages.makes.steps",
        "station_type": "ALB",
    },
    "Whitby": {
        "label": "Whitby, North Yorkshire",
        "latitude": 54.48813,
        "longitude": -0.61308,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/whitby-lifeboat-station",
        "what3words": "///number.fabric.airless",
        "station_type": "ALB",
    },
    "Whitstable": {
        "label": "Whitstable, Kent",
        "latitude": 51.36256,
        "longitude": 1.02577,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/whitstable-lifeboat-station",
        "what3words": "///landlords.author.local",
        "station_type": "ILB",
    },
    "Wick": {
        "label": "Wick, Caithness",
        "latitude": 58.43935,
        "longitude": -3.08293,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/wick-lifeboat-station",
        "what3words": "///bolsters.octagon.fell",
        "station_type": "ALB",
    },
    "Wicklow": {
        "label": "Wicklow, Wicklow",
        "latitude": 52.98164,
        "longitude": -6.03272,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/wicklow-lifeboat-station",
        "what3words": "///engineer.detergent.sandwiched",
        "station_type": "ALB",
    },
    "Withernsea": {
        "label": "Withernsea, East Riding of Yorkshire",
        "latitude": 53.72607,
        "longitude": 0.04075,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/withernsea-lifeboat-station",
        "what3words": "///patch.vandalism.sidelined",
        "station_type": "ILB",
    },
    "Workington": {
        "label": "Workington, Cumbria",
        "latitude": 54.65089,
        "longitude": -3.56769,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/workington-lifeboat-station",
        "what3words": "///status.pirate.give",
        "station_type": "ALB",
    },
    "Yarmouth (IOW)": {
        "label": "Yarmouth (IOW), Isle of Wight",
        "latitude": 50.70615,
        "longitude": -1.50048,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/yarmouth-lifeboat-station",
        "what3words": "///certainly.bashed.barefoot",
        "station_type": "ALB",
    },
    "Youghal": {
        "label": "Youghal, Cork",
        "latitude": 51.95144,
        "longitude": -7.84412,
        "url": "https://rnli.org/find-my-nearest/lifeboat-stations/youghal-lifeboat-station",
        "what3words": "///stockpiles.sudden.rank",
        "station_type": "ILB",
    },
}
