"""Static list of RNLI lifeboat stations.

Generated from the RNLI open data station locations feature service:
https://services1.arcgis.com/evM5NkxAYjTi6XPw/arcgis/rest/services/RNLI_Lifeboat_Station_locations/FeatureServer

The launches API has no station-list endpoint and only exposes the 50 most
recent launches, so this list backfills the config-flow dropdown. Names can
differ slightly from the feed's shortName (e.g. "Bangor (Co Down)" vs
"Bangor"), which is why station matching is done on normalized base names.
"""

STATIONS: dict[str, str] = {
    "Aberdeen": "Aberdeen, City of Aberdeen",
    "Aberdovey": "Aberdovey, Gwynedd",
    "Abersoch": "Abersoch, Gwynedd",
    "Aberystwyth": "Aberystwyth, Dyfed",
    "Achill Island": "Achill Island, Mayo",
    "Aith": "Aith, Shetland",
    "Aldeburgh": "Aldeburgh, Suffolk",
    "Alderney": "Alderney, Channel Isles",
    "Amble": "Amble, Northumberland",
    "Angle": "Angle, Dyfed",
    "Anstruther": "Anstruther, Fife",
    "Appledore": "Appledore, Devon",
    "Aran Islands": "Aran Islands, Galway",
    "Arbroath": "Arbroath, Angus",
    "Arklow": "Arklow, Wicklow",
    "Arran (Lamlash)": "Arran (Lamlash), Ayrshire and Arran",
    "Arranmore": "Arranmore, Donegal",
    "Ballycotton": "Ballycotton, Cork",
    "Ballyglass": "Ballyglass, Mayo",
    "Baltimore": "Baltimore, Cork",
    "Bangor (Co Down)": "Bangor (Co Down), Down",
    "Barmouth": "Barmouth, Gwynedd",
    "Barra Island": "Barra Island, Western Isles",
    "Barrow": "Barrow, Cumbria",
    "Barry Dock": "Barry Dock, South Glamorgan",
    "Beaumaris": "Beaumaris, Gwynedd",
    "Bembridge": "Bembridge, Isle of Wight",
    "Berwick-Upon-Tweed": "Berwick-Upon-Tweed, Northumberland",
    "Blackpool": "Blackpool, Lancashire",
    "Blyth": "Blyth, Northumberland",
    "Borth": "Borth, Dyfed",
    "Bridlington": "Bridlington, East Riding of Yorkshire",
    "Brighton": "Brighton, East Sussex",
    "Broughty Ferry": "Broughty Ferry, City of Dundee",
    "Buckie": "Buckie, Banffshire",
    "Bude": "Bude, Cornwall",
    "Bundoran": "Bundoran, Donegal",
    "Burnham-on-Crouch": "Burnham-on-Crouch, Essex",
    "Burnham-on-Sea": "Burnham-on-Sea, Somerset",
    "Burry Port": "Burry Port, Dyfed",
    "Calshot": "Calshot, Hampshire",
    "Campbeltown": "Campbeltown, Argyll and Bute",
    "Cardigan": "Cardigan, Dyfed",
    "Carrybridge": "Carrybridge, Fermanagh",
    "Castletownbere": "Castletownbere, Cork",
    "Chiswick": "Chiswick, Greater London",
    "Clacton-on-Sea": "Clacton-on-Sea, Essex",
    "Cleethorpes": "Cleethorpes, Lincolnshire",
    "Clifden": "Clifden, Galway",
    "Clogherhead": "Clogherhead, Louth",
    "Clovelly": "Clovelly, Devon",
    "Conwy": "Conwy, Clwyd",
    "Courtmacsherry Harbour": "Courtmacsherry Harbour, Cork",
    "Courtown": "Courtown, Wexford",
    "Cowes": "Cowes, Isle of Wight",
    "Craster": "Craster, Northumberland",
    "Criccieth": "Criccieth, Gwynedd",
    "Cromer": "Cromer, Norfolk",
    "Crosshaven": "Crosshaven, Cork",
    "Cullercoats": "Cullercoats, Tyne & Wear",
    "Dart": "Dart, Devon",
    "Donaghadee": "Donaghadee, Down",
    "Douglas": "Douglas, Isle of Man",
    "Dover": "Dover, Kent",
    "Dun Laoghaire": "Dun Laoghaire, Dublin",
    "Dunbar": "Dunbar, East Lothian",
    "Dungeness": "Dungeness, Kent",
    "Dunmore East": "Dunmore East, Waterford",
    "Eastbourne": "Eastbourne, East Sussex",
    "Enniskillen": "Enniskillen, Fermanagh",
    "Exmouth": "Exmouth, Devon",
    "Eyemouth": "Eyemouth, Berwickshire",
    "Falmouth": "Falmouth, Cornwall",
    "Fenit": "Fenit, Kerry",
    "Fethard": "Fethard, Wexford",
    "Filey": "Filey, North Yorkshire",
    "Fishguard": "Fishguard, Dyfed",
    "Flamborough": "Flamborough, East Riding of Yorkshire",
    "Fleetwood": "Fleetwood, Lancashire",
    "Flint": "Flint, Clwyd",
    "Fowey": "Fowey, Cornwall",
    "Fraserburgh": "Fraserburgh, Aberdeenshire",
    "Galway": "Galway, Galway",
    "Girvan": "Girvan, Ayrshire and Arran",
    "Gravesend": "Gravesend, Kent",
    "Great Yarmouth and Gorleston": "Great Yarmouth and Gorleston, Norfolk",
    "Happisburgh": "Happisburgh, Norfolk",
    "Hartlepool": "Hartlepool, Durham",
    "Harwich": "Harwich, Essex",
    "Hastings": "Hastings, East Sussex",
    "Hayling Island": "Hayling Island, Hampshire",
    "Helensburgh": "Helensburgh, Dunbartonshire",
    "Helvick Head": "Helvick Head, Waterford",
    "Holyhead": "Holyhead, Gwynedd",
    "Horton and Port Eynon": "Horton and Port Eynon, West Glamorgan",
    "Howth": "Howth, Dublin",
    "Hoylake": "Hoylake, Merseyside",
    "Humber": "Humber, East Riding of Yorkshire",
    "Hunstanton": "Hunstanton, Norfolk",
    "Ilfracombe": "Ilfracombe, Devon",
    "Invergordon": "Invergordon, Ross and Cromarty",
    "Islay": "Islay, Argyll and Bute",
    "Kessock": "Kessock, Ross and Cromarty",
    "Kilkeel": "Kilkeel, Down",
    "Kilmore Quay": "Kilmore Quay, Wexford",
    "Kilrush": "Kilrush, Clare",
    "Kinghorn": "Kinghorn, Fife",
    "Kinsale": "Kinsale, Cork",
    "Kippford": "Kippford, The Stewartry of Kirkcudbright",
    "Kirkcudbright": "Kirkcudbright, The Stewartry of Kirkcudbright",
    "Kirkwall": "Kirkwall, Orkney",
    "Kyle of Lochalsh": "Kyle of Lochalsh, Ross and Cromarty",
    "Largs": "Largs, Ayrshire and Arran",
    "Larne": "Larne, Antrim",
    "Lerwick": "Lerwick, Shetland",
    "Leverburgh": "Leverburgh, Western Isles",
    "Little and Broad Haven": "Little and Broad Haven, Dyfed",
    "Littlehampton": "Littlehampton, West Sussex",
    "Littlestone-on-Sea": "Littlestone-on-Sea, Kent",
    "Llandudno": "Llandudno, Clwyd",
    "Loch Ness": "Loch Ness, Inverness",
    "Lochinver": "Lochinver, Sutherland",
    "Longhope": "Longhope, Orkney",
    "Looe": "Looe, Cornwall",
    "Lough Derg": "Lough Derg, Tipperary",
    "Lough Ree": "Lough Ree, Westmeath",
    "Lough Swilly": "Lough Swilly, Donegal",
    "Lowestoft": "Lowestoft, Suffolk",
    "Lyme Regis": "Lyme Regis, Dorset",
    "Lymington": "Lymington, Hampshire",
    "Lytham St Annes": "Lytham St Annes, Lancashire",
    "Mablethorpe": "Mablethorpe, Lincolnshire",
    "Macduff": "Macduff, Banffshire",
    "Mallaig": "Mallaig, Inverness",
    "Margate": "Margate, Kent",
    "Minehead": "Minehead, Somerset",
    "Moelfre": "Moelfre, Gwynedd",
    "Montrose": "Montrose, Angus",
    "Morecambe": "Morecambe, Lancashire",
    "Mudeford": "Mudeford, Dorset",
    "New Brighton": "New Brighton, Merseyside",
    "New Quay (Ceredigion)": "New Quay (Ceredigion), Dyfed",
    "Newbiggin": "Newbiggin, Northumberland",
    "Newcastle (Co Down)": "Newcastle (Co Down), Down",
    "Newhaven": "Newhaven, East Sussex",
    "Newquay (Cornwall)": "Newquay (Cornwall), Cornwall",
    "North Berwick": "North Berwick, East Lothian",
    "Oban": "Oban, Argyll and Bute",
    "Padstow": "Padstow, Cornwall",
    "Peel": "Peel, Isle of Man",
    "Penarth": "Penarth, South Glamorgan",
    "Penlee": "Penlee, Cornwall",
    "Peterhead": "Peterhead, Aberdeenshire",
    "Plymouth": "Plymouth, Devon",
    "Poole": "Poole, Dorset",
    "Port Erin": "Port Erin, Isle of Man",
    "Port Isaac": "Port Isaac, Cornwall",
    "Port St Mary": "Port St Mary, Isle of Man",
    "Port Talbot": "Port Talbot, West Glamorgan",
    "Portaferry": "Portaferry, Down",
    "Porthcawl": "Porthcawl, Mid Glamorgan",
    "Porthdinllaen": "Porthdinllaen, Gwynedd",
    "Portishead": "Portishead, Somerset",
    "Portpatrick": "Portpatrick, Wigtown",
    "Portree": "Portree, Ross and Cromarty",
    "Portrush": "Portrush, Antrim",
    "Portsmouth": "Portsmouth, Hampshire",
    "Pwllheli": "Pwllheli, Gwynedd",
    "Queensferry": "Queensferry, City of Edinburgh",
    "Ramsey": "Ramsey, Isle of Man",
    "Ramsgate": "Ramsgate, Kent",
    "Red Bay": "Red Bay, Antrim",
    "Redcar": "Redcar, North Yorkshire",
    "Rhyl": "Rhyl, Clwyd",
    "Rock": "Rock, Cornwall",
    "Rosslare Harbour": "Rosslare Harbour, Wexford",
    "Rye Harbour": "Rye Harbour, East Sussex",
    "Salcombe": "Salcombe, Devon",
    "Scarborough": "Scarborough, North Yorkshire",
    "Seahouses": "Seahouses, Northumberland",
    "Selsey": "Selsey, West Sussex",
    "Sennen Cove": "Sennen Cove, Cornwall",
    "Sheerness": "Sheerness, Kent",
    "Sheringham": "Sheringham, Norfolk",
    "Shoreham Harbour": "Shoreham Harbour, West Sussex",
    "Silloth": "Silloth, Cumbria",
    "Skegness": "Skegness, Lincolnshire",
    "Skerries": "Skerries, Dublin",
    "Sligo Bay": "Sligo Bay, Sligo",
    "Southend-on-Sea": "Southend-on-Sea, Essex",
    "Southwold": "Southwold, Suffolk",
    "St Agnes": "St Agnes, Cornwall",
    "St Bees": "St Bees, Cumbria",
    "St Catherine": "St Catherine, Channel Isles",
    "St Davids": "St Davids, Dyfed",
    "St Helier": "St Helier, Channel Isles",
    "St Ives": "St Ives, Cornwall",
    "St Mary's": "St Mary's, Cornwall",
    "St Peter Port": "St Peter Port, Channel Isles",
    "Staithes and Runswick": "Staithes and Runswick, North Yorkshire",
    "Stonehaven": "Stonehaven, Kincardineshire",
    "Stornoway": "Stornoway, Western Isles",
    "Stranraer": "Stranraer, Wigtown",
    "Stromness": "Stromness, Orkney",
    "Sunderland": "Sunderland, Tyne & Wear",
    "Swanage": "Swanage, Dorset",
    "Teddington": "Teddington, Greater London",
    "Teignmouth": "Teignmouth, Devon",
    "Tenby": "Tenby, Dyfed",
    "The Lizard": "The Lizard, Cornwall",
    "The Mumbles": "The Mumbles, West Glamorgan",
    "Thurso": "Thurso, Caithness",
    "Tighnabruaich": "Tighnabruaich, Argyll and Bute",
    "Tobermory": "Tobermory, Argyll and Bute",
    "Torbay": "Torbay, Devon",
    "Tower": "Tower, Greater London",
    "Tramore": "Tramore, Waterford",
    "Trearddur Bay": "Trearddur Bay, Gwynedd",
    "Troon": "Troon, Ayrshire and Arran",
    "Tynemouth": "Tynemouth, Tyne & Wear",
    "Union Hall": "Union Hall, Cork",
    "Valentia": "Valentia, Kerry",
    "Walmer": "Walmer, Kent",
    "Walton and Frinton": "Walton and Frinton, Essex",
    "Wells": "Wells, Norfolk",
    "West Kirby": "West Kirby, Merseyside",
    "West Mersea": "West Mersea, Essex",
    "Weston-Super-Mare": "Weston-Super-Mare, Somerset",
    "Wexford": "Wexford, Wexford",
    "Weymouth": "Weymouth, Dorset",
    "Whitby": "Whitby, North Yorkshire",
    "Whitstable": "Whitstable, Kent",
    "Wick": "Wick, Caithness",
    "Wicklow": "Wicklow, Wicklow",
    "Withernsea": "Withernsea, East Riding of Yorkshire",
    "Workington": "Workington, Cumbria",
    "Yarmouth (IOW)": "Yarmouth (IOW), Isle of Wight",
    "Youghal": "Youghal, Cork",
}
