#!/usr/bin/env python3
"""Regenerate custom_components/rnli_launches/stations.py from RNLI open data.

Usage: python3 scripts/generate_stations.py

Downloads the RNLI lifeboat station locations layer and rewrites the bundled
station list. Stations open, close and get renamed upstream, so review the
diff before committing. Uses only the standard library.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any
import urllib.parse
import urllib.request

LAYER_URL = (
    "https://services1.arcgis.com/evM5NkxAYjTi6XPw/arcgis/rest/services/"
    "RNLI_Lifeboat_Station_locations/FeatureServer"
)
FIELDS = ("Station", "County", "URL", "StationType", "Lat", "Long", "What3Words")
OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "custom_components"
    / "rnli_launches"
    / "stations.py"
)

HEADER = f'''"""Static list of RNLI lifeboat stations.

Generated by scripts/generate_stations.py from the RNLI open data station
locations dataset ({LAYER_URL}).

The launches API has no station-list endpoint and only exposes the 50 most
recent launches, so this list backfills the config-flow dropdown. Names can
differ slightly from the feed's shortName (e.g. "Bangor (Co Down)" vs
"Bangor"), which is why station matching is done on normalized base names.
"""
from typing import Any

STATIONS: dict[str, dict[str, Any]] = {{
'''


def fetch_stations() -> list[dict[str, Any]]:
    """Download every station record from the open data layer."""
    query = urllib.parse.urlencode(
        {
            "where": "1=1",
            "outFields": ",".join(FIELDS),
            "returnGeometry": "false",
            "orderByFields": "Station",
            "resultRecordCount": 1000,
            "f": "json",
        }
    )
    with urllib.request.urlopen(f"{LAYER_URL}/0/query?{query}", timeout=30) as resp:
        data = json.load(resp)
    if "error" in data:
        raise SystemExit(f"ArcGIS returned an error: {data['error']}")
    if data.get("exceededTransferLimit"):
        raise SystemExit("More stations than one request returns; add paging")
    return [feature["attributes"] for feature in data["features"]]


def render(records: list[dict[str, Any]]) -> str:
    """Render station records as the stations.py module source."""
    stations: dict[str, dict[str, Any]] = {}
    for record in records:
        name = record["Station"].strip()
        if name in stations:
            raise SystemExit(f"Duplicate station name: {name}")
        stations[name] = {
            "label": f"{name}, {record['County'].strip()}",
            "latitude": round(record["Lat"], 5),
            "longitude": round(record["Long"], 5),
            "url": record["URL"],
            "what3words": record["What3Words"],
            "station_type": record["StationType"],
        }

    lines = [HEADER]
    for name in sorted(stations):
        lines.append(f"    {json.dumps(name, ensure_ascii=False)}: {{\n")
        for key, value in stations[name].items():
            lines.append(f'        "{key}": {json.dumps(value, ensure_ascii=False)},\n')
        lines.append("    },\n")
    lines.append("}\n")
    return "".join(lines)


def main() -> None:
    """Regenerate the station list."""
    records = fetch_stations()
    OUTPUT.write_text(render(records), encoding="utf-8")
    print(f"Wrote {len(records)} stations to {OUTPUT}")


if __name__ == "__main__":
    main()
